var lang = {
    en: {
        ones: {short: 'Ones', suggest: 'You got ones with'},
        twos: {short: 'Twos', suggest: 'You got twos with'},
        threes: {short: 'Threes', suggest: 'You got threes with'},
        fours: {short: 'Fours', suggest: 'You got fours with'},
        fives: {short: 'Fives', suggest: 'You got fives with'},
        sixes: {short: 'Sixes', suggest: 'You got sixes with'},
        pair: {short: 'One pair', suggest: 'You got one pair with'},
        twoPairs: {short: 'Two pairs', suggest: 'You got two pairs with'},
        threeKind: {short: 'Three of a kind', suggest: 'You got three of a kind with'},
        fourKind: {short: 'Four of a kind', suggest: 'You got four of a kind with'},
        sStraight: {short: 'Small straight', suggest: 'You got small straight with'},
        bStraight: {short: 'Big straight', suggest: 'You got big straight with'},
        fullHouse: {short: 'Full house', suggest: 'You got full house with'},
        chance: {short: 'Chance', suggest: 'Chance gives'},
        yatzy: {short: 'Yatzy', suggest: 'ZATZY 🎉 it gives'},
        btnAddMorePlayers: '+ add more players',
        btnStartGame: 'START GAME',
        btnRollDices: 'Roll dices',
        placeholderEnterName: 'Enter players name',
        player: 'Player',
        sum: 'Sum',
        bonus: 'Bonus',
        total: 'Total',
        select: 'Select',
        skip: 'Do you really want to skip',
        selectLanguage: 'Select language',
        noMatch: 'No match 😢 Roll again or click a score field to skip it!'
    },
    sv: {
        ones: {short: 'Ettor', suggest: 'Du har ettor med'},
        twos: {short: 'Tvår', suggest: 'Du har tvåor med'},
        threes: {short: 'Treor', suggest: 'Du har treor med'},
        fours: {short: 'Fyror', suggest: 'Du har fyror med'},
        fives: {short: 'Femmor', suggest: 'Du har femmor med'},
        sixes: {short: 'Sexor', suggest: 'Du har sexor med'},
        pair: {short: 'Ett par', suggest: 'Du har ett par med'},
        twoPairs: {short: 'Två par', suggest: 'Du har två par med'},
        threeKind: {short: 'Tretal', suggest: 'Du har tretal med'},
        fourKind: {short: 'Fyrtal', suggest: 'Du har fyrtal med'},
        sStraight: {short: 'Liten stege', suggest: 'Du har en liten stege med'},
        bStraight: {short: 'Stor stege', suggest: 'Du har en stor stege med'},
        fullHouse: {short: 'Kåk', suggest: 'Du har kåk med'},
        chance: {short: 'Chans', suggest: 'Chans ger'},
        yatzy: {short: 'Yatzy', suggest: 'ZATZY 🎉 ger'},
        btnAddMorePlayers: '+ lägg till fler spelare',
        btnStartGame: 'STARTA SPEL',
        btnRollDices: 'Rulla tärningarna',
        placeholderEnterName: 'Ange spelarens namn',
        player: 'Spelare',
        sum: 'Summa',
        bonus: 'Bonus',
        total: 'Totalt',
        select: 'Välj',
        skip: 'Vill du verkligen styrka',
        selectLanguage: 'Välj språk',
        noMatch: 'Ingen träff 😢 Rulla igen eller välj ett poäng att stryka!'
    },
    ja: {
        ones: {short: 'もの', suggest: 'あなたは'},
        twos: {short: 'ツー', suggest: 'あなたは2を持っています'},
        threes: {short: 'スリーズ', suggest: 'あなたは3を持っています'},
        fours: {short: '四つんばい', suggest: '四つんばい'},
        fives: {short: 'ファイブ', suggest: 'あなたは5を手に入れました'},
        sixes: {short: 'シックス', suggest: 'あなたはシックスを得ました'},
        pair: {short: '一組', suggest: 'あなたは一組を手に入れました'},
        twoPairs: {short: '2ペア', suggest: 'あなたは2ペアを手に入れました'},
        threeKind: {short: '種類の3つ', suggest: 'あなたは3種類の'},
        fourKind: {short: '一種の', suggest: 'あなたは4種類の'},
        sStraight: {short: '小さなストレート', suggest: 'あなたは小さなストレートを手に入れました'},
        bStraight: {short: 'ビッグストレート', suggest: 'あなたはまっすぐに大きくなりました'},
        fullHouse: {short: 'フルハウス', suggest: 'あなたは完全な家を得ました'},
        chance: {short: '機会', suggest: 'チャンスは与える'},
        yatzy: {short: 'ヤッツィー', suggest: 'ZATZY 🎉 それは与えます'},
        btnAddMorePlayers: '+プレイヤーを追加',
        btnStartGame: 'ゲームをスタート',
        btnRollDices: 'サイコロを振る',
        placeholderEnterName: 'プレイヤー名を入力してください',
        player: 'プレーヤー',
        sum: '和',
        bonus: 'ボーナス',
        total: '合計',
        select: '選択する',
        skip: '本当にスキップしますか',
        selectLanguage: '言語を選択する',
        noMatch: '歯が立たない 😢 もう一度ロールするか、スコアフィールドをクリックしてスキップしてください！'
    },
    
}
//TODO: use lang.short in yatzy.js/html 